package com.parkyc.poelens.mechanics.config;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;

class MechanicsSchemaMigrationTest {

    private JdbcTemplate jdbcTemplate;

    @BeforeEach
    void setUp() {
        jdbcTemplate = new JdbcTemplate(new DriverManagerDataSource(
                "jdbc:h2:mem:legacy-" + UUID.randomUUID() + ";DB_CLOSE_DELAY=-1", "sa", ""));
        jdbcTemplate.execute("""
                CREATE TABLE mechanics (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(255) NOT NULL,
                    game_version VARCHAR(255) NOT NULL,
                    title VARCHAR(255) NOT NULL,
                    explanation VARCHAR(2000) NOT NULL,
                    source_url VARCHAR(255) NOT NULL,
                    collected_at DATE NOT NULL,
                    reviewed BOOLEAN NOT NULL,
                    CONSTRAINT uk_legacy_mechanics UNIQUE (name, game_version)
                )
                """);
        jdbcTemplate.update("""
                INSERT INTO mechanics (name, game_version, title, explanation, source_url, collected_at, reviewed)
                VALUES ('Fireball', '3.29', 'Legacy Fireball', 'Legacy catalog row', 'https://example.com/', DATE '2026-08-11', TRUE)
                """);
    }

    @Test
    void keepsTheVersionAndSkillKeyForMechanicOverrides() {
        new MechanicsSchemaMigration(jdbcTemplate).migrate();

        assertEquals(1, jdbcTemplate.queryForObject("""
                SELECT COUNT(*) FROM mechanics
                WHERE name = 'Fireball' AND game_version = '3.29'
                """, Integer.class));
    }
}
